aws_dbt_snowflake_project:
  outputs:
    dev:
      account: XXPPDFE-MFC45644
      database: AIRBNB
      password: Abhinaya211202
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: ABHINAYA21
      warehouse: COMPUTE_WH
  target: dev
